---
- hosts: all-in-one
  vars_files:
    - "common_vars.yml"
  roles:
    - role: clean
    - role: prepare
    - role: etcd
    - role: master
    - role: flannel
    - role: docker
    - role: node
    - role: coredns
    - role: dashboard
...
